// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types generate

export interface Business {
  name: string;
  phone: string;
  email?: string;
  address?: string;
  category?: string;
  notes?: string;
  preferred_channel?: "whatsapp" | "email" | "both";
  is_active?: boolean;
}

export interface Conversation {
  user_id?: string;
  customer_id?: string;
  phone: string;
  display_name?: string;
  language?: "es" | "en" | "de" | "fr";
  order_ids?: string[];
  unread_count?: number;
  admin_unread_count?: number;
  customer_unread_count?: number;
  last_message_at?: string;
  service_window_expires_at?: string;
  automation_enabled?: boolean;
  intake_status?: "idle" | "collecting" | "created" | "needs_admin";
  intake_draft?: {
    service_type?: string;
    original_text?: string;
    translated_text?: string;
    delivery_address?: string;
    preferred_schedule?: string;
    client_notes?: string;
  };
  intake_missing_fields?: string[];
  last_intake_order_id?: string;
}

export interface Customer {
  phone: string;
  email?: string;
  user_id?: string;
  display_name?: string;
  language?: "es" | "en" | "de" | "fr";
  order_count?: number;
  last_order_at?: string;
  marketing_consent?: boolean;
}

export interface DeliveryPerson {
  /**
   * Usuario Base44 asociado al repartidor
   */
  user_id?: string;
  /**
   * Nombre del repartidor
   */
  name: string;
  /**
   * Teléfono del repartidor
   */
  phone: string;
  /**
   * Zona de reparto
   */
  zone?: string;
  /**
   * Estado activo/inactivo
   */
  is_active?: boolean;
  /**
   * Notas internas
   */
  notes?: string;
}

export interface Message {
  user_id?: string;
  customer_id?: string;
  conversation_id: string;
  order_id?: string;
  provider_sid?: string;
  in_reply_to_sid?: string;
  direction: "inbound" | "outbound" | "system";
  sender_type?: "customer" | "admin" | "system" | "whatsapp_automation";
  channel?: "in_app" | "whatsapp" | "system";
  body: string;
  status?: string;
  media_urls?: string[];
  sent_at?: string;
  automation?: boolean;
}

export interface Order {
  order_number?: string;
  public_tracking_token?: string;
  payment_token?: string;
  user_id?: string;
  customer_id?: string;
  service_type: "supermercado" | "farmacia" | "compras_personales" | "recados" | "transporte_productos";
  original_text: string;
  translated_text?: string;
  translation_mode?: "original" | "base44_ai" | "manual" | "pending";
  original_language?: string;
  client_language: "es" | "en" | "de" | "fr";
  delivery_address: string;
  client_phone: string;
  client_name?: string;
  preferred_schedule?: string;
  client_notes?: string;
  attachment_urls?: string[];
  internal_notes?: string;
  business_assignments?: {
    business_id?: string;
    business_name?: string;
    business_phone?: string;
    business_email?: string;
    preferred_channel?: string;
  }[];
  package_ids?: string[];
  order_status?:
    | "nuevo"
    | "pendiente_pago"
    | "confirmado"
    | "en_proceso"
    | "recogido"
    | "en_camino"
    | "entregado"
    | "cancelado";
  assigned_delivery?: string;
  assigned_delivery_name?: string;
  product_cost?: number;
  transport_cost?: number;
  service_cost?: number;
  total?: number;
  payment_status?: "sin_presupuestar" | "pendiente" | "pagado" | "reembolsado";
  payment_method?: "stripe" | "bizum" | "efectivo" | "transferencia";
  payment_link?: string;
  stripe_checkout_session_id?: string;
  stripe_payment_intent_id?: string;
  paid_at?: string;
  status_history?: {
    status?: string;
    at?: string;
    actor?: string;
  }[];
}

export interface ProductPackage {
  name: string;
  service_type?: string;
  description?: string;
  contents: string;
  notes?: string;
  is_active?: boolean;
}

export interface User {
  /**
   * Rol funcional dentro de W Recados. Los administradores usan el campo role integrado de Base44.
   */
  app_role?: "customer" | "courier";
  /**
   * Teléfono normalizado del usuario
   */
  phone?: string;
  language?: "es" | "en" | "de" | "fr";
  /**
   * Perfil Customer asociado cuando app_role es customer
   */
  customer_id?: string;
  /**
   * Perfil DeliveryPerson asociado cuando app_role es courier
   */
  delivery_person_id?: string;
}

declare module '@base44/sdk' {
  interface EntityTypeRegistry {
    "Business": Business;
    "Conversation": Conversation;
    "Customer": Customer;
    "DeliveryPerson": DeliveryPerson;
    "Message": Message;
    "Order": Order;
    "ProductPackage": ProductPackage;
    "User": User;
  }

  interface FunctionNameRegistry {
    "completeCustomerProfile": true;
    "createAuthenticatedOrder": true;
    "getCustomerPortal": true;
    "markManualPayment": true;
    "createStripeCheckout": true;
    "createPublicOrder": true;
    "sendCustomerMessage": true;
    "sendAdminMessage": true;
    "sendWhatsApp": true;
    "stripeWebhook": true;
    "twilioInbound": true;
    "twilioStatus": true;
  }
}
